### ISSUE TITLE
存入image的时候会报错

### ISSUE THREAD

**Issue by zuqiu123** [TonyJR/TODBModel#7]
BUG IN CLIENT OF sqlite3.dylib: illegal multi-threaded access to database connection
![image](https://user-images.githubusercontent.com/15611129/45478076-b0332a80-b775-11e8-817c-fc6ed3c2f4c5.png)

**Comment by TonyJR** [comment]
目前不支持保存UIImage类型，因为图片保存会大量占用空间，多次保存也会重复占用。
如果实在需要保存图片的话，可以转成NSData，再保存。但是不建议这样做
