### ISSUE TITLE
写的很棒 不过有很大的问题

### ISSUE THREAD

**Issue by sunchengxiu** [TonyJR/TODBModel#8]
有一个很大的 问题，就是不支持 model 里面，再存在一个对象，你的代码看起来是支持的，但是实际我测试是不可以的，比如就拿 AddressModel 来说，里面有个 name 属性，我把 name 属性删掉，新建一个 InfoModel，然后这个InfoModel里面，有个 name 属性，大概是这样的，
@property(nonatomic , strong)InfoModel *info;
@property (nonatomic,assign) int addressID;
@property (nonatomic,strong) NSDate *editDate;
@property (nonatomic,strong) NSString *mobile;
@property (nonatomic,strong) NSString *address;

然后外边改一下，在createAddress里面，改一下
for (AddressModel *model in createdModels) {
        model.editDate = [NSDate date];
        model.info = [InfoModel new];
        model.info.name = [NSString stringWithFormat:@"%@%@%@",surname[model.addressID%surname.count],cnNumber[model.addressID%100/10],cnNumber[model.addressID%10]];
        model.mobile = [NSString stringWithFormat:@"%@%08d",mobileHead[rand()%mobileHead.count],model.addressID];
        [model save:nil];
    }
然后就不可以。不知道是不是我使用的有问题，有时间您看一下，我这边试着改一下

**Comment by TonyJR** [comment]
最初设计的时候是支持的。中间有一次改版，有一些情况没考虑到。我会尽快修复这个问题。

**Comment by TonyJR** [comment]
模型嵌套时无法保存的问题已经修复
