### ISSUE TITLE
还有个问题

### ISSUE THREAD

**Issue by sunchengxiu** [TonyJR/TODBModel#9]
兄弟，你的更新速度很快，但还是有个问题，我看了下，您的修改的意思，大概是把model里面的模型又建造了一个table，我看你在userinfo里面，load里面registerTable了，这样不太科学吧，一般小型APP都是一个数据库，甚至多了的话，也没必要为一个这么小的model，建造一个数据库模型，其实我建议是否可以把建造表数据库的什么操作部分接口暴露一下，传入一个表明，或者给个方法返回yes，NO，之类的，当然您这个开源，我们可以自己改代码，我这边的想法是，最好做成其实您就做成一个表就够了，addressmodel里面的userinfo是个blob就行了，然后userinfo等，给个接口是否生成数据库就更棒了，以上是个人建议想法。

**Comment by TonyJR** [comment]
1、创建数据库的方式建议不要放在+(void)load方法里，这里我偷懒了，最好是根据业务场景在统一的位置创建
2、修改表名的接口可以通过覆盖模型类的+(NSString *)db_name方法来实现
3、稍后我会加入一个判断，当模型没有对应的数据表时，把对象直接序列化保存在BLOB里

**Comment by sunchengxiu** [comment]
Perfect，demo肯定会越来越好的




| |
孙承秀
邮箱：15699998823@163.com
|

签名由 网易邮箱大师 定制

在2018年10月09日 10:31，Tony 写道：

1、创建数据库的方式建议不要放在+(void)load方法里，这里我偷懒了，最好是根据业务场景在统一的位置创建
2、修改表名的接口可以通过覆盖模型类的+(NSString *)db_name方法来实现
3、稍后我会加入一个判断，当模型没有对应的数据表时，把对象直接序列化保存在BLOB里

**Comment by sunchengxiu** [comment]
我这边又总结了两点问题，
1.你新改的是把userinfo又存了个数据库，我不想存，就把这行代码中的save给注释了，但是就会出问题，理论上不应该有问题啊，我没想明白，可能是我代码没看全，我只会不保存 到数据库，但是这个数据还是会存到address这个数据库的
2.save 这个方法
- (void)save:(void (^)(NSObject *))block{
    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        [self db_update];
        if (block) {
            block(self);
        }
    });
    
}
你提供了一个block，而这个save方法里面又执行了[self db_update];这个方法，而这个方法也是异步的，然后回调了 block ，这样写个人觉得很大的问题，这个block回调没有意义，很大程度上block的回调会在update之前，数据库没有更新完你就回调了，所以个人剧的这个save接口还是不要block的好
3.我觉得我们可以加个联系方式了，哈哈 ，我这两天再看你这个demo

**Comment by TonyJR** [comment]
刚刚发布了1.2.2版本，可以看一下。
我的微信是：show33show

**Comment by sunchengxiu** [comment]
已加




| |
孙承秀
邮箱：15699998823@163.com
|

签名由 网易邮箱大师 定制

在2018年10月10日 17:52，Tony 写道：

刚刚发布了1.2.2版本，可以看一下。
我的微信是：show33show

**Comment by TonyJR** [comment]
非常感谢你后来提的这两个问题。
第一个问题是有计划修改的，我准备在model中提供白名单和黑名单功能，可以让用户决定哪些属性会归档到数据库，那些不需要。
第二个问题确实是存在bug，这里的本意是做二级存储。所以提取出了sql之后，没有等待真正的数据哭操作就直接回调block了。但是仔细想想，这样确实不合理。
